-- VHDL Entity ece411.ADj66.generatedInstance
--
-- Created:
--          by - ravi7.ews (linux-a1.ews.illinois.edu)
--          at - 19:55:36 03/27/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ADj66 IS
   PORT( 
      ADJ6out : OUT    LC3b_word;
      clk     : IN     std_logic;
      index6  : IN     LC3b_index6;
      RESET_L : IN     STD_LOGIC
   );

END ADj66 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF ADj66 IS 
BEGIN


END generatedInstance;
