-- VHDL Entity ece411.Arbiter.generatedInstance
--
-- Created:
--          by - aikara2.ews (gelib-057-29.ews.illinois.edu)
--          at - 18:25:40 03/19/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Arbiter IS
   PORT( 
      clk : IN     std_logic
   );

END Arbiter ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Arbiter IS 
BEGIN


END generatedInstance;
