-- VHDL Entity ece411.CacheWriter.symbol
--
-- Created:
--          by - ravi7.ews (siebl-0220-20.ews.illinois.edu)
--          at - 13:10:29 02/28/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY CacheWriter IS
   PORT( 
      LRUout4         : IN     std_logic;
      Ld_h            : IN     std_logic;
      clk             : IN     std_logic;
      hit_in          : IN     std_logic;
      prehit_in       : IN     std_logic;
      write_access_in : IN     std_logic;
      exit_dirty      : OUT    std_logic;
      setdata         : OUT    std_logic
   );

-- Declarations

END CacheWriter ;

--
-- VHDL Architecture ece411.CacheWriter.struct
--
-- Created:
--          by - ravi7.ews (siebl-0220-20.ews.illinois.edu)
--          at - 13:10:29 02/28/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY mp3lib;

ARCHITECTURE struct OF CacheWriter IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL B          : STD_LOGIC;
   SIGNAL F          : STD_LOGIC;
   SIGNAL setDataBit : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL exit_dirty_internal : std_logic;


   -- Component Declarations
   COMPONENT clock_delay
   PORT (
      clk : IN     std_logic ;
      B   : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT AND2
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT AND3
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      C : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT OR2
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AND2 USE ENTITY mp3lib.AND2;
   FOR ALL : AND3 USE ENTITY mp3lib.AND3;
   FOR ALL : OR2 USE ENTITY mp3lib.OR2;
   FOR ALL : clock_delay USE ENTITY ece411.clock_delay;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_4 : clock_delay
      PORT MAP (
         clk => clk,
         B   => B
      );
   U_0 : AND2
      PORT MAP (
         A => Ld_h,
         B => LRUout4,
         F => F
      );
   U_3 : AND2
      PORT MAP (
         A => setDataBit,
         B => B,
         F => setdata
      );
   U_2 : AND3
      PORT MAP (
         A => prehit_in,
         B => hit_in,
         C => write_access_in,
         F => exit_dirty_internal
      );
   U_1 : OR2
      PORT MAP (
         A => F,
         B => exit_dirty_internal,
         F => setDataBit
      );

   -- Implicit buffered output assignments
   exit_dirty <= exit_dirty_internal;

END struct;
