-- VHDL Entity ece411.clock_delay.generatedInstance
--
-- Created:
--          by - ravi7.ews (gelib-057-13.ews.illinois.edu)
--          at - 16:30:39 02/28/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY clock_delay IS
   PORT( 
      B   : OUT    STD_LOGIC;
      clk : IN     std_logic
   );

END clock_delay ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF clock_delay IS 
BEGIN


END generatedInstance;
