-- VHDL Entity ece411.CondNCode.generatedInstance
--
-- Created:
--          by - ravi7.ews (linux-a2.ews.illinois.edu)
--          at - 18:47:35 03/27/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY CondNCode IS
   PORT( 
      clk       : IN     std_logic;
      Gen_cc    : OUT    LC3b_cc;
      RESET_L   : IN     STD_LOGIC;
      WB_ALUout : IN     LC3b_word
   );

END CondNCode ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF CondNCode IS 
BEGIN


END generatedInstance;
