-- VHDL Entity ece411.HitorMiss.interface
--
-- Created:
--          by - aikara2.ews (gelib-057-29.ews.illinois.edu)
--          at - 18:25:39 03/19/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY HitorMiss IS
   PORT( 
      Cache_prehit  : IN     STD_LOGIC;
      access_memory : IN     STD_LOGIC;
      clk           : IN     std_logic;
      start_hit     : IN     std_logic;
      Dclk          : OUT    std_logic;
      Miss          : OUT    std_logic;
      hit           : OUT    std_logic
   );

-- Declarations

END HitorMiss ;

--
-- VHDL Architecture ece411.HitorMiss.struct1
--
-- Created:
--          by - aikara2.ews (gelib-057-29.ews.illinois.edu)
--          at - 18:25:39 03/19/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY mp3lib;

ARCHITECTURE struct1 OF HitorMiss IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL A : STD_LOGIC;
   SIGNAL F : STD_LOGIC;


   -- Component Declarations
   COMPONENT AND4
   PORT (
      A : IN     STD_LOGIC;
      B : IN     STD_LOGIC;
      C : IN     STD_LOGIC;
      D : IN     STD_LOGIC;
      F : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT ClockGate
   PORT (
      Clk : IN     std_logic ;
      A   : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT AND3
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      C : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT NOT1
   PORT (
      A : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AND3 USE ENTITY mp3lib.AND3;
   FOR ALL : AND4 USE ENTITY ece411.AND4;
   FOR ALL : ClockGate USE ENTITY ece411.ClockGate;
   FOR ALL : NOT1 USE ENTITY mp3lib.NOT1;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1      
   Dclk <= A ;                                  


   -- Instance port mappings.
   U_2 : AND4
      PORT MAP (
         A => A,
         B => access_memory,
         C => Cache_prehit,
         D => start_hit,
         F => hit
      );
   U_3 : ClockGate
      PORT MAP (
         clk => clk,
         A   => A
      );
   U_0 : AND3
      PORT MAP (
         A => F,
         B => access_memory,
         C => start_hit,
         F => Miss
      );
   U_1 : NOT1
      PORT MAP (
         A => Cache_prehit,
         F => F
      );

END struct1;
