-- VHDL Entity ece411.ID_EX.interface
--
-- Created:
--          by - ravi7.ews (linux-a1.ews.illinois.edu)
--          at - 22:46:47 03/26/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ID_EX IS
   PORT( 
      RESET_L      : IN     STD_LOGIC;
      clk          : IN     std_logic;
      Control      : IN     CONTROL_WORD;
      ID_CC        : IN     STD_LOGIC_VECTOR (2 DOWNTO 0);
      ID_IR        : IN     LC3b_word;
      ID_srcB_regB : IN     LC3b_word;
      ID_srcA_regB : IN     LC3B_WORD;
      Ex_CC        : OUT    LC3b_cc;
      Ex_IR        : OUT    LC3b_word;
      Ex_NPC       : OUT    LC3b_word;
      EX_SRCA      : OUT    STD_LOGIC_VECTOR (15 DOWNTO 0);
      EX_SRCB      : OUT    STD_LOGIC_VECTOR (15 DOWNTO 0);
      Set_regB     : IN     STD_LOGIC;
      Ex_dest_reg  : OUT    STD_LOGIC_VECTOR (2 DOWNTO 0);
      regA_pc_out  : IN     LC3b_word;
      ID_dest_reg  : IN     LC3b_reg;
      EX_CONTROL   : OUT    CONTROL_WORD
   );

-- Declarations

END ID_EX ;

--
-- VHDL Architecture ece411.ID_EX.struct
--
-- Created:
--          by - ravi7.ews (linux-a1.ews.illinois.edu)
--          at - 22:46:48 03/26/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY mp3lib;

ARCHITECTURE struct OF ID_EX IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL RESET_L1 : STD_LOGIC;


   -- Component Declarations
   COMPONENT ControlStore
   PORT (
      CLK         : IN     std_logic ;
      RESET       : IN     STD_LOGIC ;
      SET         : IN     STD_LOGIC ;
      Control_in  : IN     CONTROL_WORD ;
      Control_out : OUT    CONTROL_WORD 
   );
   END COMPONENT;
   COMPONENT REG16
   PORT (
      RESET_L : IN     STD_LOGIC ;
      A       : IN     STD_LOGIC_VECTOR (15 DOWNTO 0);
      EN      : IN     STD_LOGIC ;
      CLK     : IN     STD_LOGIC ;
      F       : OUT    STD_LOGIC_VECTOR (15 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT REG3
   PORT (
      RESET_L : IN     STD_LOGIC ;
      A       : IN     STD_LOGIC_VECTOR (2 DOWNTO 0);
      EN      : IN     STD_LOGIC ;
      CLK     : IN     STD_LOGIC ;
      F       : OUT    STD_LOGIC_VECTOR (2 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : ControlStore USE ENTITY ece411.ControlStore;
   FOR ALL : REG16 USE ENTITY mp3lib.REG16;
   FOR ALL : REG3 USE ENTITY mp3lib.REG3;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   StorageUnit : ControlStore
      PORT MAP (
         CLK         => clk,
         RESET       => RESET_L,
         SET         => Set_regB,
         Control_in  => Control,
         Control_out => EX_CONTROL
      );
   U_1 : REG16
      PORT MAP (
         RESET_L => RESET_L,
         A       => regA_pc_out,
         EN      => Set_regB,
         CLK     => clk,
         F       => Ex_NPC
      );
   U_2 : REG16
      PORT MAP (
         RESET_L => RESET_L,
         A       => ID_srcB_regB,
         EN      => Set_regB,
         CLK     => clk,
         F       => EX_SRCB
      );
   U_3 : REG16
      PORT MAP (
         RESET_L => RESET_L,
         A       => ID_srcA_regB,
         EN      => Set_regB,
         CLK     => clk,
         F       => EX_SRCA
      );
   U_4 : REG16
      PORT MAP (
         RESET_L => RESET_L,
         A       => ID_IR,
         EN      => Set_regB,
         CLK     => clk,
         F       => Ex_IR
      );
   U_0 : REG3
      PORT MAP (
         RESET_L => RESET_L,
         A       => ID_CC,
         EN      => Set_regB,
         CLK     => clk,
         F       => Ex_CC
      );
   U_5 : REG3
      PORT MAP (
         RESET_L => RESET_L1,
         A       => ID_dest_reg,
         EN      => Set_regB,
         CLK     => clk,
         F       => Ex_dest_reg
      );

END struct;
