-- VHDL Entity ece411.IFAddrPass.generatedInstance
--
-- Created:
--          by - ravi7.ews (dcl-l520-09.ews.illinois.edu)
--          at - 21:24:10 03/19/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY IFAddrPass IS
   PORT( 
      clk            : IN     std_logic;
      ifetch_address : OUT    LC3b_word;
      PCout          : IN     LC3b_word
   );

END IFAddrPass ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF IFAddrPass IS 
BEGIN


END generatedInstance;
