-- VHDL Entity ece411.InstFetch.interface
--
-- Created:
--          by - ravi7.ews (linux-a2.ews.illinois.edu)
--          at - 11:47:22 03/27/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY InstFetch IS
   PORT( 
      Branch_true_EX  : IN     STD_LOGIC;
      Load_PC         : IN     STD_LOGIC;
      PCMuxSelect_Mem : IN     std_logic;
      RESET_L         : IN     STD_LOGIC;
      TARGET_PC       : IN     LC3b_word;
      clk             : IN     std_logic;
      ifetch_datain   : IN     LC3b_word;
      ifetch_mresp_h  : IN     std_logic;
      PCPlus2out      : OUT    LC3b_word;
      ifetch_address  : OUT    LC3b_word;
      ifetch_mread_l  : OUT    std_logic;
      ifetch_out      : OUT    LC3b_word;
      ifetch_ready    : OUT    std_logic
   );

-- Declarations

END InstFetch ;

--
-- VHDL Architecture ece411.InstFetch.struct
--
-- Created:
--          by - ravi7.ews (linux-a2.ews.illinois.edu)
--          at - 11:47:23 03/27/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY mp3lib;

ARCHITECTURE struct OF InstFetch IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL F     : STD_LOGIC;
   SIGNAL Fin   : LC3b_word;
   SIGNAL PCout : LC3b_word;

   -- Implicit buffer signal declarations
   SIGNAL PCPlus2out_internal : LC3b_word;


   -- Component Declarations
   COMPONENT AND_maker
   PORT (
      A : IN     STD_LOGIC;
      B : IN     STD_LOGIC;
      F : OUT    STD_LOGIC
   );
   END COMPONENT;
   COMPONENT Add2
   PORT (
      PCout      : IN     LC3b_word ;
      clk        : IN     std_logic ;
      PCPlus2out : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT WordMux2
   PORT (
      A   : IN     LC3b_word ;
      B   : IN     LC3b_word ;
      Sel : IN     std_logic ;
      F   : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT REG16
   PORT (
      RESET_L : IN     STD_LOGIC ;
      A       : IN     STD_LOGIC_VECTOR (15 DOWNTO 0);
      EN      : IN     STD_LOGIC ;
      CLK     : IN     STD_LOGIC ;
      F       : OUT    STD_LOGIC_VECTOR (15 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AND_maker USE ENTITY ece411.AND_maker;
   FOR ALL : Add2 USE ENTITY ece411.Add2;
   FOR ALL : REG16 USE ENTITY mp3lib.REG16;
   FOR ALL : WordMux2 USE ENTITY ece411.WordMux2;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb3 3 
   ifetch_mread_l <= NOT(CLK);
   ifetch_ready <= ifetch_mresp_h;
   ifetch_out <= ifetch_datain;
   ifetch_address <= PCout;                                     


   -- Instance port mappings.
   U_2 : AND_maker
      PORT MAP (
         A => PCMuxSelect_Mem,
         B => Branch_true_EX,
         F => F
      );
   NextPc : Add2
      PORT MAP (
         PCout      => PCout,
         clk        => clk,
         PCPlus2out => PCPlus2out_internal
      );
   U_1 : WordMux2
      PORT MAP (
         A   => PCPlus2out_internal,
         B   => TARGET_PC,
         Sel => F,
         F   => Fin
      );
   U_0 : REG16
      PORT MAP (
         RESET_L => RESET_L,
         A       => Fin,
         EN      => Load_PC,
         CLK     => clk,
         F       => PCout
      );

   -- Implicit buffered output assignments
   PCPlus2out <= PCPlus2out_internal;

END struct;
