-- VHDL Entity ece411.L1CacheSet.symbol
--
-- Created:
--          by - ravi7.ews (linux-a1.ews.illinois.edu)
--          at - 01:22:45 03/28/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY L1CacheSet IS
   PORT( 
      clk       : IN     std_logic;
      ADDRESS   : IN     LC3b_word;
      MWRITEH_L : IN     std_logic;
      DataOut   : IN     LC3b_word;
      MREAD_L   : IN     std_logic;
      mwritel_l : IN     std_logic;
      RESET_L   : IN     std_logic;
      DataIn    : OUT    LC3b_word;
      PMADDRESS : OUT    LC3B_WORD;
      PMDATAOUT : OUT    LC3b_oword;
      PMDATAIN  : IN     lc3b_oword;
      PMWRITE_L : OUT    STD_LOGIC;
      PMREAD_L  : OUT    STD_LOGIC;
      PMRESP_H  : IN     STD_LOGIC;
      mresp_h   : OUT    STD_LOGIC
   );

-- Declarations

END L1CacheSet ;

--
-- VHDL Architecture ece411.L1CacheSet.struct
--
-- Created:
--          by - ravi7.ews (linux-a1.ews.illinois.edu)
--          at - 01:22:45 03/28/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF L1CacheSet IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Miss      : std_logic;
   SIGNAL start_hit : std_logic;
   SIGNAL LdOn      : std_logic;
   SIGNAL IsItDirty : STD_LOGIC;


   -- Component Declarations
   COMPONENT Cache_Controller
   PORT (
      IsItDirty : IN     STD_LOGIC ;
      Miss      : IN     std_logic ;
      PMRESP_H  : IN     STD_LOGIC ;
      RESET_L   : IN     std_logic ;
      clk       : IN     std_logic ;
      LdOn      : OUT    std_logic ;
      PMREAD_L  : OUT    STD_LOGIC ;
      PMWRITE_L : OUT    STD_LOGIC ;
      start_hit : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Cache_Datapath
   PORT (
      ADDRESS   : IN     LC3b_word ;
      DataOut   : IN     LC3b_word ;
      LdOn      : IN     std_logic ;
      MREAD_L   : IN     std_logic ;
      MWRITEH_L : IN     std_logic ;
      PMDATAIN  : IN     lc3b_oword ;
      PMRESP_H  : IN     STD_LOGIC ;
      RESET_L   : IN     std_logic ;
      clk       : IN     std_logic ;
      mwritel_l : IN     std_logic ;
      start_hit : IN     std_logic ;
      DataIn    : OUT    LC3b_word ;
      IsItDirty : OUT    STD_LOGIC ;
      Miss      : OUT    std_logic ;
      PMADDRESS : OUT    LC3B_WORD ;
      PMDATAOUT : OUT    LC3b_oword ;
      mresp_h   : OUT    STD_LOGIC 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Cache_Controller USE ENTITY ece411.Cache_Controller;
   FOR ALL : Cache_Datapath USE ENTITY ece411.Cache_Datapath;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   Cache_Cont : Cache_Controller
      PORT MAP (
         IsItDirty => IsItDirty,
         Miss      => Miss,
         PMRESP_H  => PMRESP_H,
         RESET_L   => RESET_L,
         clk       => clk,
         LdOn      => LdOn,
         PMREAD_L  => PMREAD_L,
         PMWRITE_L => PMWRITE_L,
         start_hit => start_hit
      );
   Cache_DP : Cache_Datapath
      PORT MAP (
         ADDRESS   => ADDRESS,
         DataOut   => DataOut,
         LdOn      => LdOn,
         MREAD_L   => MREAD_L,
         MWRITEH_L => MWRITEH_L,
         PMDATAIN  => PMDATAIN,
         PMRESP_H  => PMRESP_H,
         RESET_L   => RESET_L,
         clk       => clk,
         mwritel_l => mwritel_l,
         start_hit => start_hit,
         DataIn    => DataIn,
         IsItDirty => IsItDirty,
         Miss      => Miss,
         PMADDRESS => PMADDRESS,
         PMDATAOUT => PMDATAOUT,
         mresp_h   => mresp_h
      );

END struct;
