-- VHDL Entity ece411.MEM_WB.interface
--
-- Created:
--          by - ravi7.ews (linux-a1.ews.illinois.edu)
--          at - 21:31:12 03/27/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY MEM_WB IS
   PORT( 
      RESET_L         : IN     STD_LOGIC;
      clk             : IN     std_logic;
      Mem_ALU_Out     : IN     LC3b_word;
      Mem_Control_out : IN     CONTROL_WORD;
      Mem_IR_Out      : IN     LC3b_word;
      set_regD        : IN     std_logic;
      WB_Control      : OUT    CONTROL_WORD;
      WB_IR           : OUT    LC3b_word;
      WB_NextPC       : OUT    LC3b_word;
      WB_ALUout       : OUT    LC3b_word;
      dest_regD       : OUT    STD_LOGIC_VECTOR (2 DOWNTO 0);
      dest_regC       : IN     STD_LOGIC_VECTOR (2 DOWNTO 0);
      Mem_Address     : IN     LC3b_word;
      WB_MEMout       : OUT    LC3b_word;
      Mem_dataout     : IN     LC3b_word
   );

-- Declarations

END MEM_WB ;

--
-- VHDL Architecture ece411.MEM_WB.struct
--
-- Created:
--          by - ravi7.ews (linux-a1.ews.illinois.edu)
--          at - 21:31:12 03/27/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF MEM_WB IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT ControlStore
   PORT (
      CLK         : IN     std_logic ;
      RESET       : IN     STD_LOGIC ;
      SET         : IN     STD_LOGIC ;
      Control_in  : IN     CONTROL_WORD ;
      Control_out : OUT    CONTROL_WORD 
   );
   END COMPONENT;
   COMPONENT Reg16
   PORT (
      RESET  : IN     std_logic ;
      clk    : IN     std_logic ;
      input  : IN     LC3b_word ;
      load   : IN     std_logic ;
      Output : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT Reg3
   PORT (
      A       : IN     STD_LOGIC_VECTOR (2 DOWNTO 0);
      CLK     : IN     STD_LOGIC;
      EN      : IN     STD_LOGIC;
      RESET_L : IN     STD_LOGIC;
      F       : OUT    STD_LOGIC_VECTOR (2 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : ControlStore USE ENTITY ece411.ControlStore;
   FOR ALL : Reg16 USE ENTITY ece411.Reg16;
   FOR ALL : Reg3 USE ENTITY ece411.Reg3;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_4 : ControlStore
      PORT MAP (
         CLK         => clk,
         RESET       => RESET_L,
         SET         => set_regD,
         Control_in  => Mem_Control_out,
         Control_out => WB_Control
      );
   U_0 : Reg16
      PORT MAP (
         RESET  => RESET_L,
         clk    => clk,
         input  => Mem_Address,
         load   => set_regD,
         Output => WB_NextPC
      );
   U_1 : Reg16
      PORT MAP (
         RESET  => RESET_L,
         clk    => clk,
         input  => Mem_ALU_Out,
         load   => set_regD,
         Output => WB_ALUout
      );
   U_2 : Reg16
      PORT MAP (
         RESET  => RESET_L,
         clk    => clk,
         input  => Mem_IR_Out,
         load   => set_regD,
         Output => WB_IR
      );
   U_5 : Reg16
      PORT MAP (
         RESET  => RESET_L,
         clk    => clk,
         input  => Mem_dataout,
         load   => set_regD,
         Output => WB_MEMout
      );
   U_3 : Reg3
      PORT MAP (
         RESET_L => RESET_L,
         A       => dest_regC,
         EN      => set_regD,
         CLK     => clk,
         F       => dest_regD
      );

END struct;
