-- VHDL Entity ece411.mp3_cpu.symbol
--
-- Created:
--          by - ravi7.ews (linux-a1.ews.illinois.edu)
--          at - 02:49:23 03/31/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY mp3_cpu IS
   PORT( 
      RESET_L : IN     std_logic
   );

-- Declarations

END mp3_cpu ;

--
-- VHDL Architecture ece411.mp3_cpu.struct
--
-- Created:
--          by - ravi7.ews (linux-a1.ews.illinois.edu)
--          at - 02:49:23 03/31/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF mp3_cpu IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL D_ADDRESS   : LC3b_word;
   SIGNAL D_DATAIN    : LC3B_WORD;
   SIGNAL D_DataOut   : LC3b_word;
   SIGNAL D_MREAD_L   : std_logic;
   SIGNAL D_MRESP_H   : STD_LOGIC;
   SIGNAL D_MWRITEH_L : std_logic;
   SIGNAL D_MWRITEL_L : std_logic;
   SIGNAL I_ADDRESS   : LC3b_word;
   SIGNAL I_DataIn    : LC3b_word;
   SIGNAL I_MREAD_L   : std_logic;
   SIGNAL I_MRESP_H   : std_logic;
   SIGNAL clk         : std_logic := '0';


   -- Component Declarations
   COMPONENT CLKgen
   PORT (
      clk : INOUT  std_logic  := '0'
   );
   END COMPONENT;
   COMPONENT CacheMoney
   PORT (
      D_ADDRESS   : IN     LC3b_word ;
      D_DataOut   : IN     LC3b_word ;
      D_MREAD_L   : IN     std_logic ;
      D_MWRITEH_L : IN     std_logic ;
      D_MWRITEL_L : IN     std_logic ;
      I_ADDRESS   : IN     LC3b_word ;
      I_MREAD_L   : IN     std_logic ;
      RESET_L     : IN     std_logic ;
      clk         : IN     std_logic ;
      D_DATAIN    : OUT    LC3B_WORD ;
      D_MRESP_H   : OUT    STD_LOGIC ;
      I_DataIn    : OUT    LC3b_word ;
      I_MRESP_H   : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT WIFDEM
   PORT (
      DATA_DATAIN    : IN     LC3b_word ;
      RESET_L        : IN     STD_LOGIC ;
      clk            : IN     std_logic ;
      data_mresp_h   : IN     std_logic ;
      ifetch_datain  : IN     LC3b_word ;
      ifetch_mresp_h : IN     std_logic ;
      DATA_ADDRESS   : OUT    LC3b_word ;
      DATA_DATAOUT   : OUT    LC3b_word ;
      DATA_MREAD_L   : OUT    std_logic ;
      DATA_MWRITEH_L : OUT    std_logic ;
      DATA_MWRITEL_L : OUT    std_logic ;
      ifetch_address : OUT    LC3b_word ;
      ifetch_mread_l : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : CLKgen USE ENTITY ece411.CLKgen;
   FOR ALL : CacheMoney USE ENTITY ece411.CacheMoney;
   FOR ALL : WIFDEM USE ENTITY ece411.WIFDEM;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   I0 : CLKgen
      PORT MAP (
         clk => clk
      );
   MainCacheMemory : CacheMoney
      PORT MAP (
         D_ADDRESS   => D_ADDRESS,
         D_DataOut   => D_DataOut,
         D_MREAD_L   => D_MREAD_L,
         D_MWRITEH_L => D_MWRITEH_L,
         D_MWRITEL_L => D_MWRITEL_L,
         I_ADDRESS   => I_ADDRESS,
         I_MREAD_L   => I_MREAD_L,
         RESET_L     => RESET_L,
         clk         => clk,
         D_DATAIN    => D_DATAIN,
         D_MRESP_H   => D_MRESP_H,
         I_DataIn    => I_DataIn,
         I_MRESP_H   => I_MRESP_H
      );
   TheDatapath : WIFDEM
      PORT MAP (
         DATA_DATAIN    => D_DATAIN,
         DATA_MRESP_H   => D_MRESP_H,
         RESET_L        => RESET_L,
         clk            => clk,
         ifetch_datain  => I_DataIn,
         ifetch_mresp_h => I_MRESP_H,
         DATA_ADDRESS   => D_ADDRESS,
         DATA_DATAOUT   => D_DataOut,
         DATA_MREAD_L   => D_MREAD_L,
         DATA_MWRITEH_L => D_MWRITEH_L,
         DATA_MWRITEL_L => D_MWRITEL_L,
         ifetch_address => I_ADDRESS,
         ifetch_mread_l => I_MREAD_L
      );

END struct;
