-- VHDL Entity ece411.NZPdoubleDecoder.generatedInstance
--
-- Created:
--          by - ravi7.ews (linux-a2.ews.illinois.edu)
--          at - 18:47:34 03/27/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY NZPdoubleDecoder IS
   PORT( 
      A       : OUT    STD_LOGIC;
      A1      : OUT    STD_LOGIC;
      A2      : OUT    STD_LOGIC;
      B       : OUT    STD_LOGIC;
      B1      : OUT    STD_LOGIC;
      B2      : OUT    STD_LOGIC;
      clk     : IN     std_logic;
      Mem_CC  : IN     LC3b_reg;
      NZP     : IN     LC3b_cc;
      RESET_L : IN     STD_LOGIC
   );

END NZPdoubleDecoder ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF NZPdoubleDecoder IS 
BEGIN


END generatedInstance;
