-- VHDL Entity ece411.OneSig.generatedInstance
--
-- Created:
--          by - ravi7.ews (dcl-l520-09.ews.illinois.edu)
--          at - 21:19:02 03/19/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY OneSig IS
   PORT( 
      A       : OUT    STD_LOGIC;
      clk     : IN     std_logic;
      RESET_L : IN     STD_LOGIC
   );

END OneSig ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF OneSig IS 
BEGIN


END generatedInstance;
