-- VHDL Entity ece411.StallingUnit.interface
--
-- Created:
--          by - ravi7.ews (linux-a1.ews.illinois.edu)
--          at - 19:47:17 03/26/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY StallingUnit IS
   PORT( 
      RESET_L        : IN     STD_LOGIC;
      clk            : IN     std_logic;
      ifetch_mresp_h : IN     std_logic;
      Load_PC        : OUT    STD_LOGIC;
      Set_regB       : OUT    STD_LOGIC;
      set_regA       : OUT    std_logic;
      set_regC       : OUT    std_logic;
      set_regD       : OUT    std_logic
   );

-- Declarations

END StallingUnit ;

--
-- VHDL Architecture ece411.StallingUnit.struct
--
-- Created:
--          by - ravi7.ews (linux-a1.ews.illinois.edu)
--          at - 19:47:17 03/26/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY mp3lib;

ARCHITECTURE struct OF StallingUnit IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Loader : STD_LOGIC;
   SIGNAL dout   : STD_LOGIC;


   -- Component Declarations
   COMPONENT AND2
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : AND2 USE ENTITY mp3lib.AND2;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1    
   Load_PC <= loader;
   set_regA <= loader;
   set_regB <= loader;
   set_regC <= loader;
   set_regD <= loader;
                                      


   -- ModuleWare code(v1.9) for instance 'U_1' of 'vdd'
   dout <= '1';

   -- Instance port mappings.
   U_0 : AND2
      PORT MAP (
         A => dout,
         B => ifetch_mresp_h,
         F => Loader
      );

END struct;
