-- VHDL Entity ece411.WriteBack.interface
--
-- Created:
--          by - ravi7.ews (linux-a1.ews.illinois.edu)
--          at - 01:09:42 03/27/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY WriteBack IS
   PORT( 
      RESET_L     : IN     STD_LOGIC;
      WB_ALUout   : IN     LC3b_word;
      WB_Control  : IN     CONTROL_WORD;
      WB_IR       : IN     LC3b_word;
      WB_MEMout   : IN     LC3b_word;
      WB_NextPC   : IN     LC3b_word;
      clk         : IN     std_logic;
      dest_regD   : IN     STD_LOGIC_VECTOR (2 DOWNTO 0);
      Cond_Code   : OUT    std_logic_vector (2 DOWNTO 0);
      Reg_DATAIN  : OUT    LC3b_word;
      Set_cc      : OUT    STD_LOGIC;
      dest_reg    : OUT    LC3b_reg;
      set_regfile : OUT    STD_LOGIC
   );

-- Declarations

END WriteBack ;

--
-- VHDL Architecture ece411.WriteBack.struct
--
-- Created:
--          by - ravi7.ews (linux-a1.ews.illinois.edu)
--          at - 01:09:42 03/27/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF WriteBack IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dataMuXsel : std_logic_vector(1 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL Reg_DATAIN_internal : LC3b_word;


   -- Component Declarations
   COMPONENT Control_slice
   PORT (
      Control_ID  : IN     CONTROL_WORD;
      RESET_L     : IN     STD_LOGIC;
      clk         : IN     std_logic;
      ALUop_ID    : OUT    LC3b_aluop;
      LD_reg_h    : OUT    std_logic;
      PCMuxSel    : OUT    STd_logic;
      Set_cc_h    : OUT    std_logic;
      dataMuXsel  : OUT    std_logic_vector (1 DOWNTO 0);
      mread_l     : OUT    std_logic;
      mwriteh_l   : OUT    std_logic;
      mwritel_l   : OUT    std_logic;
      srcb_select : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT GenCondCode
   PORT (
      RESET_L    : IN     STD_LOGIC ;
      Reg_DATAIN : IN     LC3b_word ;
      clk        : IN     std_logic ;
      Cond_Code  : OUT    std_logic_vector (2 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT WordMux4
   PORT (
      Input00 : IN     LC3b_word ;
      Input01 : IN     LC3b_word ;
      Input10 : IN     LC3b_word ;
      Input11 : IN     LC3b_word ;
      Select4 : IN     std_logic_vector (1 DOWNTO 0);
      Fin     : OUT    LC3b_word 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Control_slice USE ENTITY ece411.Control_slice;
   FOR ALL : GenCondCode USE ENTITY ece411.GenCondCode;
   FOR ALL : WordMux4 USE ENTITY ece411.WordMux4;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1  
   dest_reg <= dest_regD;                                      


   -- Instance port mappings.
   U_0 : Control_slice
      PORT MAP (
         Control_ID  => WB_Control,
         RESET_L     => RESET_L,
         clk         => clk,
         ALUop_ID    => OPEN,
         dataMuXsel  => dataMuXsel,
         LD_reg_h    => set_regfile,
         Set_cc_h    => Set_cc,
         PCMuxSel    => OPEN,
         mread_l     => OPEN,
         mwritel_l   => OPEN,
         mwriteh_l   => OPEN,
         srcb_select => OPEN
      );
   aGenCondCode : GenCondCode
      PORT MAP (
         RESET_L    => RESET_L,
         Reg_DATAIN => Reg_DATAIN_internal,
         clk        => clk,
         Cond_Code  => Cond_Code
      );
   DataMux : WordMux4
      PORT MAP (
         Input00 => WB_NextPC,
         Input01 => WB_NextPC,
         Input10 => WB_MEMout,
         Input11 => WB_ALUout,
         Select4 => dataMuXsel,
         Fin     => Reg_DATAIN_internal
      );

   -- Implicit buffered output assignments
   Reg_DATAIN <= Reg_DATAIN_internal;

END struct;
