-- VHDL Entity ece411.ZeroOne.generatedInstance
--
-- Created:
--          by - ravi7.ews (linux-a1.ews.illinois.edu)
--          at - 13:03:20 03/23/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ZeroOne IS
   PORT( 
      clk      : IN     std_logic;
      RESET_L  : IN     STD_LOGIC;
      zeroOne1 : OUT    std_logic_vector (1 DOWNTO 0)
   );

END ZeroOne ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF ZeroOne IS 
BEGIN


END generatedInstance;
